-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS tourism.accommodation_amenities
(
    accommodation_id bigint NOT NULL,
    amenity_id integer NOT NULL,
    CONSTRAINT accommodation_amenities_pkey PRIMARY KEY (accommodation_id, amenity_id)
);

CREATE TABLE IF NOT EXISTS tourism.accommodation_types
(
    accommodation_type_id serial NOT NULL,
    type_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT accommodation_types_pkey PRIMARY KEY (accommodation_type_id),
    CONSTRAINT accommodation_types_type_name_key UNIQUE (type_name)
);

CREATE TABLE IF NOT EXISTS tourism.accommodations
(
    accommodation_id bigserial NOT NULL,
    owner_id bigint NOT NULL,
    accommodation_type_id integer NOT NULL,
    location_id bigint NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    max_guests integer NOT NULL,
    bedroom_count integer NOT NULL DEFAULT 1,
    bathroom_count integer NOT NULL DEFAULT 1,
    base_price_per_night numeric(10, 2) NOT NULL,
    currency_code character(3) COLLATE pg_catalog."default" NOT NULL DEFAULT 'USD'::bpchar,
    check_in_time time without time zone,
    check_out_time time without time zone,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT accommodations_pkey PRIMARY KEY (accommodation_id)
);

CREATE TABLE IF NOT EXISTS tourism.amenities
(
    amenity_id serial NOT NULL,
    amenity_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT amenities_pkey PRIMARY KEY (amenity_id),
    CONSTRAINT amenities_amenity_name_key UNIQUE (amenity_name)
);

CREATE TABLE IF NOT EXISTS tourism.booking_guests
(
    booking_guest_id bigserial NOT NULL,
    booking_id bigint NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    age integer,
    document_number character varying(50) COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT booking_guests_pkey PRIMARY KEY (booking_guest_id)
);

CREATE TABLE IF NOT EXISTS tourism.booking_statuses
(
    booking_status_id serial NOT NULL,
    status_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT booking_statuses_pkey PRIMARY KEY (booking_status_id),
    CONSTRAINT booking_statuses_status_name_key UNIQUE (status_name)
);

CREATE TABLE IF NOT EXISTS tourism.bookings
(
    booking_id bigserial NOT NULL,
    guest_id bigint NOT NULL,
    accommodation_id bigint NOT NULL,
    room_id bigint,
    booking_status_id integer NOT NULL,
    check_in_date date NOT NULL,
    check_out_date date NOT NULL,
    adult_count integer NOT NULL DEFAULT 1,
    child_count integer NOT NULL DEFAULT 0,
    total_nights integer GENERATED ALWAYS AS ((check_out_date - check_in_date)) STORED,
    subtotal_amount numeric(10, 2) NOT NULL,
    tax_amount numeric(10, 2) NOT NULL DEFAULT 0,
    discount_amount numeric(10, 2) NOT NULL DEFAULT 0,
    total_amount numeric(10, 2) NOT NULL,
    special_requests text COLLATE pg_catalog."default",
    booking_reference character varying(50) COLLATE pg_catalog."default" NOT NULL,
    booked_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT bookings_pkey PRIMARY KEY (booking_id),
    CONSTRAINT bookings_booking_reference_key UNIQUE (booking_reference)
);

CREATE TABLE IF NOT EXISTS tourism.guests
(
    guest_id bigserial NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(150) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(30) COLLATE pg_catalog."default",
    date_of_birth date,
    nationality character varying(100) COLLATE pg_catalog."default",
    passport_number character varying(50) COLLATE pg_catalog."default",
    emergency_contact_name character varying(150) COLLATE pg_catalog."default",
    emergency_contact_phone character varying(30) COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT guests_pkey PRIMARY KEY (guest_id),
    CONSTRAINT guests_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS tourism.locations
(
    location_id bigserial NOT NULL,
    country character varying(100) COLLATE pg_catalog."default" NOT NULL,
    state character varying(100) COLLATE pg_catalog."default",
    city character varying(100) COLLATE pg_catalog."default" NOT NULL,
    district character varying(100) COLLATE pg_catalog."default",
    address_line1 character varying(150) COLLATE pg_catalog."default" NOT NULL,
    address_line2 character varying(150) COLLATE pg_catalog."default",
    postal_code character varying(20) COLLATE pg_catalog."default",
    latitude numeric(9, 6),
    longitude numeric(9, 6),
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT locations_pkey PRIMARY KEY (location_id)
);

CREATE TABLE IF NOT EXISTS tourism.owners
(
    owner_id bigserial NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    company_name character varying(150) COLLATE pg_catalog."default",
    email character varying(150) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(30) COLLATE pg_catalog."default",
    tax_id character varying(50) COLLATE pg_catalog."default",
    address_line1 character varying(150) COLLATE pg_catalog."default",
    address_line2 character varying(150) COLLATE pg_catalog."default",
    city character varying(100) COLLATE pg_catalog."default",
    state character varying(100) COLLATE pg_catalog."default",
    country character varying(100) COLLATE pg_catalog."default",
    postal_code character varying(20) COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT owners_pkey PRIMARY KEY (owner_id),
    CONSTRAINT owners_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS tourism.payments
(
    payment_id bigserial NOT NULL,
    booking_id bigint NOT NULL,
    payment_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    amount numeric(10, 2) NOT NULL,
    payment_method character varying(50) COLLATE pg_catalog."default" NOT NULL,
    payment_status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    transaction_reference character varying(100) COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payments_pkey PRIMARY KEY (payment_id)
);

CREATE TABLE IF NOT EXISTS tourism.reviews
(
    review_id bigserial NOT NULL,
    booking_id bigint NOT NULL,
    guest_id bigint NOT NULL,
    accommodation_id bigint NOT NULL,
    rating integer NOT NULL,
    review_title character varying(150) COLLATE pg_catalog."default",
    review_text text COLLATE pg_catalog."default",
    review_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reviews_pkey PRIMARY KEY (review_id),
    CONSTRAINT reviews_booking_id_key UNIQUE (booking_id)
);

CREATE TABLE IF NOT EXISTS tourism.rooms
(
    room_id bigserial NOT NULL,
    accommodation_id bigint NOT NULL,
    room_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    room_code character varying(50) COLLATE pg_catalog."default",
    floor_number integer,
    capacity integer NOT NULL,
    bed_count integer NOT NULL DEFAULT 1,
    room_price_per_night numeric(10, 2),
    is_available boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT rooms_pkey PRIMARY KEY (room_id),
    CONSTRAINT uq_room_code_per_accommodation UNIQUE (accommodation_id, room_code)
);

CREATE TABLE IF NOT EXISTS tourism.staff_users
(
    staff_user_id bigserial NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(150) COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    role_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT staff_users_pkey PRIMARY KEY (staff_user_id),
    CONSTRAINT staff_users_email_key UNIQUE (email)
);

ALTER TABLE IF EXISTS tourism.accommodation_amenities
    ADD CONSTRAINT fk_accommodation_amenity_accommodation FOREIGN KEY (accommodation_id)
    REFERENCES tourism.accommodations (accommodation_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS tourism.accommodation_amenities
    ADD CONSTRAINT fk_accommodation_amenity_amenity FOREIGN KEY (amenity_id)
    REFERENCES tourism.amenities (amenity_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS tourism.accommodations
    ADD CONSTRAINT fk_accommodation_location FOREIGN KEY (location_id)
    REFERENCES tourism.locations (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_accommodations_location_id
    ON tourism.accommodations(location_id);


ALTER TABLE IF EXISTS tourism.accommodations
    ADD CONSTRAINT fk_accommodation_owner FOREIGN KEY (owner_id)
    REFERENCES tourism.owners (owner_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_accommodations_owner_id
    ON tourism.accommodations(owner_id);


ALTER TABLE IF EXISTS tourism.accommodations
    ADD CONSTRAINT fk_accommodation_type FOREIGN KEY (accommodation_type_id)
    REFERENCES tourism.accommodation_types (accommodation_type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS tourism.booking_guests
    ADD CONSTRAINT fk_booking_guest_booking FOREIGN KEY (booking_id)
    REFERENCES tourism.bookings (booking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS tourism.bookings
    ADD CONSTRAINT fk_booking_accommodation FOREIGN KEY (accommodation_id)
    REFERENCES tourism.accommodations (accommodation_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_bookings_accommodation_id
    ON tourism.bookings(accommodation_id);


ALTER TABLE IF EXISTS tourism.bookings
    ADD CONSTRAINT fk_booking_guest FOREIGN KEY (guest_id)
    REFERENCES tourism.guests (guest_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_bookings_guest_id
    ON tourism.bookings(guest_id);


ALTER TABLE IF EXISTS tourism.bookings
    ADD CONSTRAINT fk_booking_room FOREIGN KEY (room_id)
    REFERENCES tourism.rooms (room_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_bookings_room_id
    ON tourism.bookings(room_id);


ALTER TABLE IF EXISTS tourism.bookings
    ADD CONSTRAINT fk_booking_status FOREIGN KEY (booking_status_id)
    REFERENCES tourism.booking_statuses (booking_status_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_bookings_status_id
    ON tourism.bookings(booking_status_id);


ALTER TABLE IF EXISTS tourism.payments
    ADD CONSTRAINT fk_payment_booking FOREIGN KEY (booking_id)
    REFERENCES tourism.bookings (booking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_payments_booking_id
    ON tourism.payments(booking_id);


ALTER TABLE IF EXISTS tourism.reviews
    ADD CONSTRAINT fk_review_accommodation FOREIGN KEY (accommodation_id)
    REFERENCES tourism.accommodations (accommodation_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_reviews_accommodation_id
    ON tourism.reviews(accommodation_id);


ALTER TABLE IF EXISTS tourism.reviews
    ADD CONSTRAINT fk_review_booking FOREIGN KEY (booking_id)
    REFERENCES tourism.bookings (booking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS reviews_booking_id_key
    ON tourism.reviews(booking_id);


ALTER TABLE IF EXISTS tourism.reviews
    ADD CONSTRAINT fk_review_guest FOREIGN KEY (guest_id)
    REFERENCES tourism.guests (guest_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_reviews_guest_id
    ON tourism.reviews(guest_id);


ALTER TABLE IF EXISTS tourism.rooms
    ADD CONSTRAINT fk_room_accommodation FOREIGN KEY (accommodation_id)
    REFERENCES tourism.accommodations (accommodation_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_rooms_accommodation_id
    ON tourism.rooms(accommodation_id);

END;

--CONSULTAS DE LA BASE DE DATOS TOURIS_ACCOMMODATION--
1. INSERTAR UN NUEVO PROPIETARIO
INSERT INTO tourism.owners (
    first_name, 
    last_name, 
    company_name, 
    email, 
    phone, 
    tax_id, 
    address_line1, 
    address_line2, 
    city, 
    state, 
    country, 
    postal_code
) VALUES (
    'Carlos', 
    'Méndez', 
    'Méndez Hospitality S.A. de C.V.', 
    'carlos.mendez@email.com', 
    '+503 7000-1111', 
    '0614-010180-123-4', 
    'Colonia Escalón, Calle El Mirador', 
    'Edificio Torre Sur, Nivel 3, Local 5', 
    'San Salvador', 
    'San Salvador', 
    'El Salvador', 
    '1101'
);

--2. INSERTAR UN NUEVO ALOJAMIENTO VINCULADO--
INSERT INTO tourism.accommodations (
    owner_id, 
    accommodation_type_id, 
    location_id, 
    name, 
    description, 
    max_guests, 
    bedroom_count, 
    bathroom_count, 
    base_price_per_night, 
    check_in_time, 
    check_out_time
) VALUES (
    1, -- ID del propietario (ej. Carlos Méndez que insertamos antes)
    3, -- ID del tipo de alojamiento (ej. 3 podría ser 'Cabaña')
    15, -- ID de la ubicación (ej. El Boquerón, San Salvador)
    'Cabaña Entre Pinos', 
    'Hermosa cabaña rústica rodeada de naturaleza con clima fresco, ideal para desconectarse de la ciudad.', 
    6, -- Capacidad máxima de huéspedes
    3, -- Número de habitaciones
    2, -- Número de baños
    125.50, -- Precio base por noche
    '15:00:00', -- Hora de Check-in (3:00 PM)
    '11:00:00'  -- Hora de Check-out (11:00 AM)
);

--3. INSERTAR HUESPED Y RESERVA--
INSERT INTO tourism.guests (
    first_name, 
    last_name, 
    email, 
    phone, 
    date_of_birth, 
    nationality, 
    passport_number, 
    emergency_contact_name, 
    emergency_contact_phone
) VALUES (
    'Elena', 
    'Martínez', 
    'elena.martinez@email.com', 
    '+503 7999-8888', 
    '1992-08-14', 
    'Salvadoreña', 
    'A12345678', 
    'Roberto Martínez', 
    '+503 7000-1111'
);

WITH nuevo_huesped AS (
    -- Paso A: Insertamos el huésped y pedimos que nos devuelva su ID
    INSERT INTO tourism.guests (first_name, last_name, email, phone, nationality)
    VALUES ('Carlos', 'Rivera', 'carlos.rivera@email.com', '+503 7777-8888', 'Salvadoreño')
    RETURNING guest_id
)
-- Paso B: Usamos ese ID devuelto para insertar la reserva inmediatamente
INSERT INTO tourism.bookings (
    guest_id, 
    accommodation_id, 
    booking_status_id, 
    check_in_date, 
    check_out_date, 
    adult_count, 
    child_count, 
    subtotal_amount, 
    tax_amount, 
    discount_amount, 
    total_amount, 
    booking_reference
)
SELECT 
    guest_id,      -- Aquí tomamos el ID que generó el paso anterior
    1,             -- ID del alojamiento
    2,             -- ID del estado de la reserva
    '2026-08-01',  -- Fecha de entrada
    '2026-08-05',  -- Fecha de salida
    2,             -- Adultos
    0,             -- Niños
    500.00,        -- Subtotal
    65.00,         -- Impuestos
    0.00,          -- Descuentos
    565.00,        -- Total
    'RES-2026-003' -- Referencia única
FROM nuevo_huesped;


--4. REGISTRAR PAGO--
INSERT INTO tourism.payments (
    booking_id, 
    amount, 
    payment_method, 
    payment_status, 
    transaction_reference, 
    notes
) VALUES (
    1,                       -- ID de la reserva a la que pertenece el pago
    565.00,                  -- Monto total pagado (debe coincidir con la reserva)
    'Credit Card',           -- Método de pago (ej. 'Credit Card', 'PayPal', 'Cash')
    'Completed',             -- Estado del pago (ej. 'Completed', 'Pending')
    'TXN-987654321-CC',      -- (Opcional) Número de referencia del banco o pasarela
    'Pago inicial completo realizado mediante tarjeta de crédito Visa.' -- (Opcional) Notas extras
);

--5 FILTRAR ALOJAMIENTOS ACTIVOS--
SELECT 
    accommodation_id AS ID,
    name AS Nombre_Alojamiento,
    max_guests AS Capacidad_Maxima,
    base_price_per_night AS Precio_Por_Noche,
    is_active AS Estado_Activo
FROM tourism.accommodations
WHERE is_active = TRUE
ORDER BY name ASC;

-- 6. Huéspedes por país,	Filtrar por nacionalidad--
SELECT 
    guest_id AS ID,
    first_name AS Nombre,
    last_name AS Apellido,
    email AS Correo,
    nationality AS Nacionalidad
FROM tourism.guests
WHERE nationality = 'Salvadoreña' -- Puedes cambiar esto por 'Estadounidense', 'Mexicana', etc.
ORDER BY first_name ASC;

--7. Reservas por fechas, 	Uso de BETWEEN
SELECT 
    booking_id AS ID_Reserva,
    guest_id AS ID_Huesped,
    accommodation_id AS ID_Alojamiento,
    check_in_date AS Fecha_Entrada,
    check_out_date AS Fecha_Salida,
    total_amount AS Total_Pagado
FROM tourism.bookings
WHERE check_in_date BETWEEN '2026-06-01' AND '2026-06-30'
ORDER BY check_in_date ASC;

--8. Actualizar precio, Modificar precio--

UPDATE tourism.accommodations
SET base_price_per_night = 150.00
WHERE accommodation_id = 1;

--9. --CAMBIAR ESTADO DE RESERVA DE 1 A 3--
UPDATE tourism.bookings
SET booking_status_id = 3  -- Cambiamos el estado (ej. 3 = Cancelada)
WHERE booking_id = 1;      -- ID de la reserva que queremos afectar

--10. ELEMINAR RESEÑA, DELETE WHERE--
DELETE FROM tourism.reviews
WHERE review_id = 5;

  --11. INER JOIN DE LA TABLAS RESERVAS + HUESPED--
SELECT 
    b.booking_id AS ID_Reserva,
    g.first_name AS Nombre_Huesped,
    g.last_name AS Apellido_Huesped,
    g.email AS Correo,
    b.check_in_date AS Fecha_Entrada,
    b.check_out_date AS Fecha_Salida,
    b.total_amount AS Total_Pagado
FROM tourism.bookings b
INNER JOIN tourism.guests g ON b.guest_id = g.guest_id
ORDER BY b.check_in_date ASC;




--12. INER JOIN COMPLETO UNIENDO ALOJAMIENTOS COMPLETOS CON 4 TABLAS--
SELECT 
    a.accommodation_id AS ID_Alojamiento,
    a.name AS Nombre_Alojamiento,
    t.type_name AS Tipo,
    o.first_name || ' ' || o.last_name AS Propietario,
    l.city AS Ciudad,
    l.country AS Pais,
    a.base_price_per_night AS Precio_Noche
FROM tourism.accommodations a
-- Primer puente: Traer el tipo de alojamiento
INNER JOIN tourism.accommodation_types t ON a.accommodation_type_id = t.accommodation_type_id
-- Segundo puente: Traer al dueño
INNER JOIN tourism.owners o ON a.owner_id = o.owner_id
-- Tercer puente: Traer la ubicación
INNER JOIN tourism.locations l ON a.location_id = l.location_id
ORDER BY a.name ASC;

--13. JOIN combinado para mostrar pagos y reservas correspondientes a los clientes--
SELECT 
    p.payment_id AS ID_Pago,
    b.booking_reference AS Codigo_Reserva,
    g.first_name || ' ' || g.last_name AS Cliente,
    g.email AS Correo_Cliente,
    p.amount AS Monto_Pagado,
    p.payment_date AS Fecha_Pago,
    p.payment_status AS Estado_Pago,
    b.total_amount AS Total_Reserva
FROM tourism.payments p
INNER JOIN tourism.bookings b ON p.booking_id = b.booking_id
INNER JOIN tourism.guests g ON b.guest_id = g.guest_id
ORDER BY p.payment_date DESC;

--14. Nos interesa saber qué reservas ya finalizaron pero el huésped aún no ha dejado ninguna reseña utilizando LEFT JOIN--

SELECT 
    b.booking_id AS ID_Reserva,
    b.booking_reference AS Codigo_Reserva,
    b.check_out_date AS Fecha_Salida,
    r.review_id AS ID_Resena,
    r.rating AS Calificacion,
    r.review_text AS Comentario_Huesped
FROM tourism.bookings b
LEFT JOIN tourism.reviews r ON b.booking_id = r.booking_id
WHERE r.review_id IS NULL
ORDER BY b.check_out_date DESC;

--15. Propiedades están registradas en el sistema pero nunca han recibido una sola reservaL, EF JOIN son reservas y filtrando null--
SELECT 
    a.accommodation_id AS ID_Alojamiento,
    a.name AS Nombre_Alojamiento,
    a.base_price_per_night AS Precio_Noche,
    b.booking_id AS ID_Reserva
FROM tourism.accommodations a
LEFT JOIN tourism.bookings b ON a.accommodation_id = b.accommodation_id
WHERE b.booking_id IS NULL
ORDER BY a.name ASC;

--16 Consulta AGG	Total ingresos	SUM--
SELECT SUM(amount) AS ingresos_totales
FROM tourism.payments
WHERE payment_status = 'Completed';

--17. Consulta AGG Promedio rating AVG--
SELECT ROUND(AVG(rating), 2) AS promedio_calificaciones
FROM tourism.reviews;

--18. Consulta AGG Top alojamientos COUNT + LIMIT --
SELECT 
    a.accommodation_id AS ID,
    a.name AS Nombre_Alojamiento,
    COUNT(b.booking_id) AS Total_Reservas
FROM tourism.accommodations a
INNER JOIN tourism.bookings b ON a.accommodation_id = b.accommodation_id
GROUP BY a.accommodation_id, a.name
ORDER BY Total_Reservas DESC
LIMIT 5;

--19. únicamente los huéspedes que son clientes frecuentes Consulta HAVING Más de 3 reservas GROUP BY + HAVING--

SELECT 
    g.guest_id AS ID_Huesped,
    g.first_name || ' ' || g.last_name AS Cliente,
    COUNT(b.booking_id) AS Total_Reservas
FROM tourism.guests g
INNER JOIN tourism.bookings b ON g.guest_id = b.guest_id
GROUP BY g.guest_id, g.first_name, g.last_name
HAVING COUNT(b.booking_id) >= 3
ORDER BY Total_Reservas DESC;

--20. Mostrar  Subconsulta Alojamiento más caro Subquery--
SELECT 
    accommodation_id AS ID,
    name AS Nombre_Alojamiento,
    base_price_per_night AS Precio_Maximo
FROM tourism.accommodations
WHERE base_price_per_night = (
    SELECT MAX(base_price_per_night) 
    FROM tourism.accommodations
);

